# Generated by Django 2.2.24 on 2021-06-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuvem', '0011_documento_stopwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='nome',
            field=models.CharField(max_length=60, verbose_name='Nome do(a) pesquisador(a)'),
        ),
    ]
