# Generated by Django 2.2.28 on 2022-06-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuvem', '0013_documento_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='font_type',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Font Type'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='select',
            field=models.CharField(blank=True, choices=[('Português', 'Português'), ('Espanhol', 'Espanhol'), ('Inglês', 'Inglês')], max_length=12, null=True),
        ),
    ]
