# Generated by Django 2.2.28 on 2022-06-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuvem', '0013_documento_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='select',
            field=models.CharField(blank=True, choices=[('Português', 'Português'), ('Espanhol', 'Espanhol'), ('Inglês', 'Inglês')], max_length=12, null=True),
        ),
    ]
