# Generated by Django 2.2.28 on 2022-06-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuvem', '0013_documento_select'),
    ]

    operations = [
    ]
