# Generated by Django 2.2.28 on 2022-07-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuvem', '0014_auto_20220613_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='font_type',
            field=models.CharField(blank=True, choices=[('Carlito-Regular.ttf', 'Carlito'), ('Comfortaa Bold.ttf', 'Comfortaa-Bold'), ('Cooper Regular.ttf', 'Cooper'), ('Dyuthi.ttf', 'Dyuthi'), ('Lato-Regular.ttf', 'Lato-Regular'), ('Poppins-Regular.ttf', 'Poppins')], default='Lato-Regular.ttf', max_length=40, null=True, verbose_name='Font Type'),
        ),
    ]
