# Generated by Django 2.2.28 on 2022-07-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuvem', '0015_documento_font_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='font_type',
            field=models.CharField(blank=True, choices=[('Carlito-Regular.ttf', 'Carlito'), ('Comfortaa Bold.ttf', 'Comfortaa-Bold'), ('Cooper Regular.ttf', 'Cooper'), ('Dyuthi.ttf', 'Dyuthi'), ('Lato-Regular.ttf', 'Lato-Regular'), ('Poppins-Regular.ttf', 'Poppins')], max_length=40, null=True, verbose_name='Font Type'),
        ),
    ]
