# Generated by Django 2.2.28 on 2022-07-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuvem', '0016_auto_20220712_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='font_type',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Font Type'),
        ),
    ]
