# Generated by Django 2.2.28 on 2022-08-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuvem', '0016_documento_consolidado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='select',
        ),
        migrations.AlterField(
            model_name='documento',
            name='language',
            field=models.CharField(blank=True, choices=[('pt', 'Português'), ('es', 'Espanhol'), ('en', 'Inglês')], max_length=5, null=True, verbose_name='Linguagem'),
        ),
    ]
