# Generated by Django 2.2.28 on 2022-07-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuvem', '0017_auto_20220713_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='font_type',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Tipo de Fonte'),
        ),
    ]
