# Generated by Django 2.2.28 on 2022-08-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuvem', '0022_auto_20220808_0957'),
        ('nuvem', '0017_auto_20220815_1100'),
    ]

    operations = [
    ]
